{% set name = "pypiserver" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypiserver-{{ version }}.zip
  sha256: 70760efadc3d89b3e1b3f54f078a6520f6c6a0c3dd718b46cd0cf466c9fd01b2

build:
  entry_points:
    - pypi-server=pypiserver.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3
    - setuptools
    - setuptools-git >=0.3
    - wheel >=0.25.0
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3

test:
  imports:
    - pypiserver
  commands:
    - pip check
    - pypi-server --help
  requires:
    - pip

about:
  home: https://github.com/pypiserver/pypiserver
  summary: A minimal PyPI server for use with pip/easy_install.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jtpio
