{% set name = "pypiserver" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0dc0e8300c12c855253b36b34beebfc28305c2c9e39151540a2886b641d4b456

build:
  entry_points:
    - pypi-server=pypiserver.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-git >=0.3
    - wheel >=0.25.0
  run:
    - python >={{ python_min }}
    - pip >=7

test:
  imports:
    - pypiserver
  commands:
    - pip check
    - pypi-server --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pypiserver/pypiserver
  summary: A minimal PyPI server for use with pip/easy_install.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jtpio
